name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag my_website
      
  - name: Login to Google Cloud 
      uses: google-github-actions/setup-gcloud@master
      with:
      version: 'latest'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
        
    - name: Deploy to Cloud Run
  gcloud run deploy webapp \
--image=us-docker.pkg.dev/cloudrun/container/webapp \
--allow-unauthenticated \
--service-account=new-serv@vivid-case-393515.iam.gserviceaccount.com \
--max-instances=10 \
--region=us-central1 \
--project=vivid-case-393515
